### ISSUE TITLE
DNN 8.0.4 Documents 7.0.1 : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by DJREIT** [DNNCommunity/DNN.Documents#8] opened 2019-03-25 23:06 UTC
After installation of Documents 7.0.1 I seem to be getting a critical error. Here is the EventLog. Can anyone shed some light on this?

`AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:6d4f8afe-2e27-4c01-8489-0bdf637a3577
AssemblyVersion:8.0.4
PortalId:1
UserId:64
TabId:143
RawUrl:/IT.aspx
Referrer:http://MYSITE/Host/Extensions/tabid/36/portalid/1/Default.aspx
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
ExceptionHash:3OyrEXqj7Xg9kVRIdKfQaw==
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at ASP.desktopmodules_documents_document_ascx.Tokenize(String strContent, ModuleInfo modInfo, Boolean forceDebug, Boolean bRevertToDnn)
   at ASP.desktopmodules_documents_document_ascx.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: MYSERVER`

**Comment by valadas** [comment] 2019-03-28 00:55
Hi @DJREIT I have just added the symbols file to the last release, can you take this file https://github.com/DNNCommunity/DNN.Documents/releases/download/07.01.00/DotNetNuke.Modules.Documents.pdb

Put it in you bin folder and reproduce the bug again, this should add some helpful details to this error log, then post it back here and we will try to find what is wrong. Thanks.

**Comment by DJREIT** [comment] 2019-03-28 04:47
I installed an reinstalled the modules and the problem seemed to have settled. One interesting thing that happened was that all of a sudden, ghost Document and HTML modules shows up on my pages. I was able to remove them and all seem stable now.

**Comment by mitchelsellers** [comment] 2020-08-06 18:49
I've tested this issue and it seems to be a post upgrade issue. Closing for now

**Closed as completed by mitchelsellers** 2020-08-06 18:49 UTC
